import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../../components/aboutus/Hero";
import Navbar from "../../components/Navbar";
import { AddOnServices } from "../../components/services/AddOnServices";
import ServiceEventsDEtails from "../../components/services/ServiceEventsDEtails";
import ServicesEventsCarousal from "../../components/services/ServicesEventsCarousal";
import ServiceHero from "../../components/services/ServicesHero";

const Services: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#fcf3ea] items-center">
        <Navbar />
        <ServiceHero />
        {/* <Hero /> */}
        <ServicesEventsCarousal />
        <AddOnServices />
        <ServiceEventsDEtails />
      </div>
    </div>
  );
};

export default Services;
