import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../../components/aboutus/Hero";
import MeetTheFounders from "../../components/aboutus/MeetTheFounders";
import Navbar from "../../components/Navbar";
import Devider from "../../components/ui/Devider";
const AboutUsPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#fcf3ea] items-center">
        <Navbar />
        <Hero />
        <Devider />
        <MeetTheFounders />
      </div>
    </div>
  );
};

export default AboutUsPage;
