import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../../components/Navbar";
const Blogs: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
    </div>
  );
};

export default Blogs;
